service: <service_name_here>

plugins:
  - serverless-plugin-typescript
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1
  environment:
    APP_SECRET: ${ssm:APP_SECRET_${self:custom.stage}}
    CLIENT_ID: ${ssm:client_id_${self:custom.stage}}
    CLIENT_SECRET: ${ssm:client_secret_${self:custom.stage}}
    NODE_ENV: ${self:custom.stage}
    NOTIFICATIONS_URI: ${ssm:notifications_uri}
    DATABASE_NAME: ${ssm:dbname_${self:custom.stage}}
    DATABASE_PASSWORD: ${ssm:dbpass_${self:custom.stage}}
    DATABASE_PORT: ${ssm:dbport_${self:custom.stage}}
    DATABASE_HOST: ${ssm:dbhost_${self:custom.stage}}
    DATABASE_USER: ${ssm:dbuser_${self:custom.stage}}
  apiName: ${self:custom.project}-${opt:stage, self:provider.stage, 'dev'}
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.project}-${self:custom.stage}-api-id
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.project}-${self:custom.stage}-api-root-id
  stackName: ${self:custom.project}-${self:service.name}-${self:custom.stage}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ssm:GetParameters'
      Resource: 'arn:aws:ssm:ap-southeast-1:#{AWS::AccountId}:parameter/*'

custom:
  stage: ${opt:stage, self:provider.stage}
  project: <project_name_here>

functions:
  index:
    handler: handler.index
    events:
      - http:
          method: get
          cors: true
          path: index
  create:
    handler: handler.create
    events:
      - http:
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - kasl-key
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
          path: enter-post-path
  update:
    handler: handler.update
    events:
      - http:
          method: any
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - kasl-key
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
          path: enter-get-path/{identifier}
          request:
            parameters:
              paths:
                identifier: true
