service: <project_name_here>-api

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1

custom:
  stage: ${opt:stage, self:provider.stage}
  project: <project_name_here>

resources:
  Resources:
    ApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ApiGateway-${self:custom.stage}

    WebsocketApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: WebsocketApi-${self:custom.stage}
        ProtocolType: WEBSOCKET
        RouteSelectionExpression: '$request.body.action'

  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGateway
      Export:
        Name: ${self:custom.project}-${self:custom.stage}-api-id

    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGateway
          - RootResourceId
      Export:
        Name: ${self:custom.project}-${self:custom.stage}-api-root-id

    WebsocketApiId:
      Value:
        Ref: WebsocketApi
      Export:
        Name: ${self:custom.project}-${self:custom.stage}-websocketapi-id
