service: sitrep

plugins:
  - serverless-plugin-typescript
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1
  environment:
    APP_SECRET: ${ssm:APP_SECRET_${self:custom.stage}}
    NODE_ENV: ${self:custom.stage}
    DATABASE_NAME: ${ssm:dbname_${self:custom.stage}}
    DATABASE_PASSWORD: ${ssm:dbpass_${self:custom.stage}}
    DATABASE_PORT: ${ssm:dbport_${self:custom.stage}}
    DATABASE_HOST: ${ssm:dbhost_${self:custom.stage}}
    DATABASE_USER: ${ssm:dbuser_${self:custom.stage}}
  apiName: ${self:custom.project}-${opt:stage, self:provider.stage, 'dev'}
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.project}-${self:custom.stage}-api-id
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.project}-${self:custom.stage}-api-root-id
  stackName: ${self:custom.project}-${self:service.name}-${self:custom.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameters"
      Resource: "arn:aws:ssm:ap-southeast-1:#{AWS::AccountId}:parameter/*"

custom:
  stage: ${opt:stage, self:provider.stage}
  project: <project_name_here>

functions:
  sitrep:
    handler: handler.sitrep
    events:
      - http:
          method: get
          cors: true
          path: sitrep
