export const sub_categories = [
  {
    name: 'Aircraft incident with injury',
    category: 'Aircraft Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Aircraft incident with damage',
    category: 'Aircraft Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Aircraft incident with damage - Wildlife',
    category: 'Aircraft Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Aircraft incident with damage - FOD',
    category: 'Aircraft Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Aircraft incident without damage',
    category: 'Aircraft Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Non-compliant pushback',
    category: 'Aircraft Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Non-compliant towing',
    category: 'Aircraft Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Non-compliant taxiing',
    category: 'Aircraft Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Overshoot/Undershoot stop line',
    category: 'Aircraft Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Arrival into incorrect stand',
    category: 'Aircraft Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Others',
    category: 'Aircraft Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Condition of fuel pit',
    category: 'Aircraft-Fuel Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Emergency fuel switch (E-stop)',
    category: 'Aircraft-Fuel Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Fuel hydrant system',
    category: 'Aircraft-Fuel Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Fuel quality',
    category: 'Aircraft-Fuel Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Others',
    category: 'Aircraft-Fuel Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Activation of fire alarm',
    category: 'Facility Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'ADGS-related',
    category: 'Facility Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Airfield lighting system',
    category: 'Facility Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Apron floodlight',
    category: 'Facility Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Damage to infrastructure',
    category: 'Facility Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'PLB-related',
    category: 'Facility Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Prolonged closure of aircraft stand',
    category: 'Facility Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Takeover of new aircraft stand',
    category: 'Facility Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Others',
    category: 'Facility Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Foreign airport closure',
    category: 'Flow Ops',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Flow restriction',
    category: 'Flow Ops',
    report_template: 'Flow Restriction',
    created_by: 0,
  },
  {
    name: 'Others',
    category: 'Flow Ops',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Air return',
    category: 'Ops Exigencies',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Diversion',
    category: 'Ops Exigencies',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Full Emergency',
    category: 'Ops Exigencies',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Local Action',
    category: 'Ops Exigencies',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Local Standby',
    category: 'Ops Exigencies',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Ramp return',
    category: 'Ops Exigencies',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Others',
    category: 'Others',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Aircraft holding for bay',
    category: 'Service Lapses',
    report_template: 'Aircraft Holding',
    created_by: 0,
  },
  {
    name: 'Late reporting - ADGS Operator',
    category: 'Service Lapses',
    report_template: 'Late Reporting',
    created_by: 0,
  },
  {
    name: 'Late reporting - Engineer/Headset man',
    category: 'Service Lapses',
    report_template: 'Late Reporting',
    created_by: 0,
  },
  {
    name: 'Late reporting - PLB Operator',
    category: 'Service Lapses',
    report_template: 'Late Reporting',
    created_by: 0,
  },
  {
    name: 'Others',
    category: 'Service Lapses',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'CEO / DM3999 / VVIP',
    category: 'Special Facilitation',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Follow me service',
    category: 'Special Facilitation',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'New aircraft type',
    category: 'Special Facilitation',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'New airline',
    category: 'Special Facilitation',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Spillage - Aircraft fuel',
    category: 'Spillage',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Spillage - Hydraulic fluid',
    category: 'Spillage',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Spillage - Oil',
    category: 'Spillage',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Spillage - Vehicle/Equipment fuel',
    category: 'Spillage',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Spillage - Other substances',
    category: 'Spillage',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Others',
    category: 'Spillage',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Vehicle failing to give way to aircraft',
    category: 'Vehicle Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Collision with injury',
    category: 'Vehicle Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Collision without injury',
    category: 'Vehicle Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'ERA infringement',
    category: 'Vehicle Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Vehicle/Equipment breakdown',
    category: 'Vehicle Related',
    report_template: 'Default',
    created_by: 0,
  },
  {
    name: 'Others',
    category: 'Vehicle Related',
    report_template: 'Default',
    created_by: 0,
  },
]
